---
- name: "Check if original config file exists"
  ansible.builtin.stat:
    path: "{{ filebeat_config_file }}"
  register: check_file_name_original
  tags:
    - backup-config


- name: "Check if backup config file exists"
  ansible.builtin.stat:
    path: "{{ filebeat_config_file }}.defaultconfig"
  register: check_file_name_backup
  tags:
    - backup-config


- name: "Backup original config file to {{ filebeat_config_file }}.defaultconfig"
  ansible.builtin.copy:
    remote_src: true
    src: "{{ filebeat_config_file }}"
    dest: "{{ filebeat_config_file }}.defaultconfig"
  when: >
      check_file_name_original.stat.exists and
      not check_file_name_backup.stat.exists
  tags:
    - backup-config